### ISSUE TITLE
Exception during cmvm compile

### ISSUE THREAD

**Issue by h2000** [ToToTec/cmvn#9]
I have build successfully cmvn from source (with cmvn 1.8) and then I tried to build cmvn with the new cmvn.

After fixing two issues in the cmvn.conf files:
-configClass is deprecated since Cmvn 0.2.0. Please use "configClass" instead.
requireCmvn is deprecated since Cmvn 0.2.0. Please use "-requireCmvn" instead.

The commands  cmvn ---configure; cmvn clean install results in the following Exception:
`
Exception in thread "main" java.lang.IllegalArgumentException: The class de.tototec.cmvn.CmvnConfiguredInputState does not have a property named: inputFilesWithTimeStamp
    at com.esotericsoftware.yamlbeans.YamlConfig.setPropertyElementType(YamlConfig.java:84)
    at de.tototec.cmvn.CmvnConfiguredInputState.fromYamlFile(CmvnConfiguredInputState.scala:51)
    at de.tototec.cmvn.ConfiguredCmvnProject.isUpToDate(ConfiguredCmvnProject.scala:121)
    at de.tototec.cmvn.ConfiguredCmvnProject.generate(ConfiguredCmvnProject.scala:159)
    at de.tototec.cmvn.ConfiguredCmvnProject$$anonfun$generateRecursive$1.apply(ConfiguredCmvnProject.scala:155)
    at de.tototec.cmvn.ConfiguredCmvnProject$$anonfun$generateRecursive$1.apply(ConfiguredCmvnProject.scala:155)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at de.tototec.cmvn.ConfiguredCmvnProject.generateRecursive(ConfiguredCmvnProject.scala:155)
    at de.tototec.cmvn.CmvnApp2$.upToDateProject(CmvnApp2.scala:173)
    at de.tototec.cmvn.CmvnApp2$.runMaven(CmvnApp2.scala:198)
    at de.tototec.cmvn.CmvnApp2$.main(CmvnApp2.scala:108)
    at de.tototec.cmvn.CmvnApp2.main(CmvnApp2.scala)
`

**Comment by lefou** [comment]
Looks like some incompatible behaviour change between yamlbeans 1.06 and 1.09. Could you please change version to 1.06 in `cmvncommon.conf` and try again?

**Comment by h2000** [comment]
It works with yaml 1.06! :) thx a lot!!

**Comment by lefou** [comment]
Nice. I'll cut a new release with this fix. Thanks for reporting!
